
// This file has been generated by the GUI designer. Do not modify.

public partial class PreferencesWindow
{
	private global::Gtk.Notebook tabs;
	private global::Gtk.Fixed fixedAccountArea;
	private global::Gtk.Label labelAccount;
	private global::Gtk.Label labelTabAccount;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textviewMessages;
	private global::Gtk.Label labelTabMessages;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget PreferencesWindow
		this.Name = "PreferencesWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Mybox Preferences");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child PreferencesWindow.Gtk.Container+ContainerChild
		this.tabs = new global::Gtk.Notebook ();
		this.tabs.CanFocus = true;
		this.tabs.Name = "tabs";
		this.tabs.CurrentPage = 0;
		// Container child tabs.Gtk.Notebook+NotebookChild
		this.fixedAccountArea = new global::Gtk.Fixed ();
		this.fixedAccountArea.Name = "fixedAccountArea";
		this.fixedAccountArea.HasWindow = false;
		// Container child fixedAccountArea.Gtk.Fixed+FixedChild
		this.labelAccount = new global::Gtk.Label ();
		this.labelAccount.Name = "labelAccount";
		this.labelAccount.LabelProp = global::Mono.Unix.Catalog.GetString ("Account:");
		this.fixedAccountArea.Add (this.labelAccount);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixedAccountArea [this.labelAccount]));
		w1.X = 38;
		w1.Y = 50;
		this.tabs.Add (this.fixedAccountArea);
		// Notebook tab
		this.labelTabAccount = new global::Gtk.Label ();
		this.labelTabAccount.Name = "labelTabAccount";
		this.labelTabAccount.LabelProp = global::Mono.Unix.Catalog.GetString ("Account");
		this.tabs.SetTabLabel (this.fixedAccountArea, this.labelTabAccount);
		this.labelTabAccount.ShowAll ();
		// Container child tabs.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewMessages = new global::Gtk.TextView ();
		this.textviewMessages.CanFocus = true;
		this.textviewMessages.Name = "textviewMessages";
		this.GtkScrolledWindow.Add (this.textviewMessages);
		this.tabs.Add (this.GtkScrolledWindow);
		global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.tabs [this.GtkScrolledWindow]));
		w4.Position = 1;
		// Notebook tab
		this.labelTabMessages = new global::Gtk.Label ();
		this.labelTabMessages.Name = "labelTabMessages";
		this.labelTabMessages.LabelProp = global::Mono.Unix.Catalog.GetString ("Messages");
		this.tabs.SetTabLabel (this.GtkScrolledWindow, this.labelTabMessages);
		this.labelTabMessages.ShowAll ();
		this.Add (this.tabs);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 478;
		this.DefaultHeight = 406;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
